saved_state = "./state.json"
log_level = "info"
log_target = "stdout"
command_socket = "/Users/geal/dev/rust/projects/yxorp/bin/command_folder/sock"
command_buffer_size = 16384
max_command_buffer_size = 163840
worker_count = 1
max_connections = 20000
max_buffers = 1000
buffer_size = 16384

[[listeners]]
address = "0.0.0.0:80"
protocol = "http"
#expect_proxy = true

[[listeners]]
address = "0.0.0.0:443"
protocol = "https"
answers = { "404" = "./assets/custom_404.html" }
tls_versions = ["TLS_V12"]

[[listeners]]
address = "0.0.0.0:1234"
protocol = "tcp"
expect_proxy = true

[clusters]
[clusters.MyCluster]
protocol = "http"
answers = { "503" = "./assets/custom_503.html" }
#sticky_session = false
#https_redirect = false
frontends = [
  { address = "0.0.0.0:80", hostname = "lolcatho.st" },
  { address = "0.0.0.0:443", hostname = "lolcatho.st", certificate = "./assets/certificate.pem", key = "./assets/key.pem" }
]
backends = [
  { address = "127.0.0.1:1026", weight = 100, sticky_id = "backend-1026" },
  { address = "127.0.0.1:1027", weight = 100, sticky_id = "backend-1027" }
]

[clusters.example_com]
protocol = "http"
frontends = [
  { address = "0.0.0.0:81", hostname = "example.com" }
]
backends = [
  { address = "127.0.0.1:1028", weight = 100 }
]

[clusters.TcpCluster]
protocol = "tcp"
#send_proxy = false
frontends = [
  { address = "0.0.0.0:8080" },
  { address = "0.0.0.0:8081" }
]
backends = [
  { address = "127.0.0.1:1029", weight = 100 },
  { address = "127.0.0.1:1030", weight = 100 }
]


