[package]
name = "sozu-command-lib"
description = "configuration library to command a sozu instance"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozu-command-lib"
homepage = "http://sozu.io"
version = "0.4.0"
license = "AGPL-3.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
categories = ["network-programming"]

include = [
  "README.md",
  "Cargo.toml",
  "/src",
]

[lib]

[dependencies]
hex = "^0.2"
log = "^0.3"
pem = "^0.4"
mio = "^0.6"
mio-uds = "^0.6"
pool = "^0.1"
toml = "^0.4"
sha2 = "^0.7"
serde = "^1.0.2"
serde_json = "^1.0.1"
serde_derive = "^1.0.2"

[features]
unstable = []

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }
