[package]
name = "sozu-command-lib"
description = "configuration library to command a sozu instance"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozu-command-lib"
homepage = "https://sozu.io"
version = "1.0.6"
license = "LGPL-3.0"
authors = [
  "Geoffroy Couprie <geo.couprie@gmail.com>",
  "Eloi Demolis <eloi.demolis@clever-cloud.com>",
  "Emmanuel Bosquet <emmanuel.bosquet@clever-cloud.com>",
  "Florentin Dubois <florentin.dubois@clever-cloud.com>",
]
categories = ["network-programming"]
edition = "2021"
rust-version = "1.80.0"
include = [
  "./README.md",
  "Cargo.toml",
  "src/**/*",
  "assets/certificate.pem",
  "assets/key.pem",
  "assets/404.html",
  "assets/503.html",
]

[dependencies]
hex = "^0.4.3"
libc = "^0.2.159"
log = "^0.4.22"
time = "^0.3.36"
toml = "^0.8.19"
memchr = "^2.7.4"
mio = { version = "^1.0.2", features = ["os-poll", "net"] }
nix = { version = "^0.29.0", features = ["socket", "uio"] }
nom = "^7.1.3"
prost = "^0.13.3"
rand = "^0.8.5"
rusty_ulid = "^2.0.0"
serde = { version = "^1.0.210", features = ["derive"] }
serde_json = "^1.0.128"
sha2 = "^0.10.8"
trailer = "^0.1.2"
prettytable-rs = { version = "^0.10.0", default-features = false }
pool = "^0.1.4"
poule = "^0.3.2"
thiserror = "^2.0.3"
x509-parser = "^0.16.0"

[features]
unstable = []
logs-debug = []
logs-trace = []

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }

[build-dependencies]
prost-build = { version = "^0.13.3" }
