[package]
name = "sozu-command-lib"
description = "configuration library to command a sozu instance"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozu-command-lib"
homepage = "http://sozu.io"
version = "0.2.0"
license = "AGPL-3.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
categories = ["network-programming"]

[dependencies]
log = "^0.3"
serde = "^1.0.2"
serde_json = "^1.0.1"
serde_derive = "^1.0.2"
openssl = "^0.9.5"
sozu-lib = { version = "^0.2", path = "../lib" }

[dependencies.toml]
version = "^0.4"
default-features = false
features = ["serde"]

[features]
unstable = []

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }
