[package]
name = "sozu-command-lib"
description = "configuration library to command a sozu instance"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozu-command-lib"
homepage = "http://sozu.io"
version = "0.13.6"
license = "LGPL-3.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
categories = ["network-programming"]
edition="2018"
include = [
  "./README.md",
  "Cargo.toml",
  "src/**/*",
  "assets/certificate.pem",
  "assets/key.pem",
  "assets/404.html",
  "assets/503.html"
]

[dependencies]
anyhow = "^1.0.59"
hex = "^0.4.3"
libc = "^0.2.126"
log = "^0.4.17"
time = "^0.3.11"
toml = "^0.5.9"
memchr = "^2.5.0"
mio = { version = "^0.8.4", features = [ "os-poll", "net" ] }
nix = "^0.23.1"
nom = "^7.1.1"
pem = "^1.0.2"
regex = "^1.6.0"
rand = "^0.8.5"
serde = { version = "^1.0.139", features = ["derive"] }
serde_json = "^1.0.82"
sha2 = "^0.10.2"
trailer = "^0.1.2"
pool = "^0.1.4"
poule = "^0.3.2"

[features]
unstable = []
logs-debug = []
logs-trace = []

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }
