[package]
name = "sozu-command-lib"
description = "configuration library to command a sozu instance"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozu-command-lib"
homepage = "http://sozu.io"
version = "0.14.2"
license = "LGPL-3.0"
authors = [
  "Geoffroy Couprie <geo.couprie@gmail.com>",
  "Eloi Demolis <eloi.demolis@clever-cloud.com>",
  "Emmanuel Bosquet <emmanuel.bosquet@clever-cloud.com>",
  "Florentin Dubois <florentin.dubois@clever-cloud.com>",
]
categories = ["network-programming"]
edition = "2021"
include = [
  "./README.md",
  "Cargo.toml",
  "src/**/*",
  "assets/certificate.pem",
  "assets/key.pem",
  "assets/404.html",
  "assets/503.html",
]

[dependencies]
anyhow = "^1.0.69"
hex = "^0.4.3"
libc = "^0.2.139"
log = "^0.4.17"
time = "^0.3.17"
toml = "^0.7.1"
memchr = "^2.5.0"
mio = { version = "^0.8.5", features = ["os-poll", "net"] }
nix = "^0.26.2"
nom = "^7.1.3"
pem = "^1.1.1"
rand = "^0.8.5"
serde = { version = "^1.0.152", features = ["derive"] }
serde_json = "^1.0.92"
sha2 = "^0.10.6"
trailer = "^0.1.2"
pool = "^0.1.4"
poule = "^0.3.2"

[features]
unstable = []
logs-debug = []
logs-trace = []

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }
