[package]
name = "sozu-command-lib"
description = "configuration library to command a sozu instance"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozu-command-lib"
homepage = "http://sozu.io"
version = "0.12.0"
license = "AGPL-3.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
categories = ["network-programming"]
edition="2018"

include = [
  "./README.md",
  "Cargo.toml",
  "src/**/*",
  "assets/certificate.pem",
  "assets/key.pem",
  "assets/404.html",
  "assets/503.html"
]

[dependencies]
hex = "^0.4"
log = "^0.4"
pem = "^0.8"
nix = "^0.15"
mio = { version = "^0.7", features = [ "os-poll", "tcp", "uds" ] }
libc = "^0.2"
pool = "^0.1"
time = "^0.2"
toml = "^0.5"
sha2 = "^0.9"
memchr = "2.3"
serde = "^1.0.34"
serde_json = "^1.0.34"
serde_derive = "^1.0.34"
trailer = {version = "^0.1.2" }
poule = "0.3"

[features]
unstable = []
logs-debug = []
logs-trace = []

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }
