[package]
name = "sozu-command-lib"
description = "configuration library to command a sozu instance"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozu-command-lib"
homepage = "http://sozu.io"
version = "0.11.0"
license = "AGPL-3.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
categories = ["network-programming"]

include = [
  "./README.md",
  "Cargo.toml",
  "src/**/*",
  "assets/certificate.pem",
  "assets/key.pem",
  "assets/404.html",
  "assets/503.html"
]

[dependencies]
hex = "^0.3"
log = "^0.4"
pem = "^0.5"
nix = "^0.11"
mio = "^0.6"
mio-uds = "^0.6"
libc = "^0.2"
pool = "^0.1"
time = "^0.1.34"
toml = "^0.4"
sha2 = "^0.8"
serde = "^1.0.2"
serde_json = "^1.0.1"
serde_derive = "^1.0.2"

[features]
unstable = []
logs-debug = []
logs-trace = []

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }
