[package]
name = "sozu-e2e"
version = "1.1.1"
rust-version = "1.82.0"
edition = "2021"

[dependencies]
futures = { workspace = true }
hyper = { workspace = true, features = ["client", "http1"] }
hyper-rustls = { workspace = true, features = ["webpki-tokio", "http1", "tls12", "logging"] }
libc = { workspace = true }
mio = { workspace = true }
rustls = { version = "^0.21.10", features = ["dangerous_configuration"] }
time = { workspace = true }
tokio = { workspace = true, features = ["net", "rt-multi-thread"] }

sozu-command-lib = { workspace = true }
sozu-lib = { workspace = true }
