[package]
name = "sozu-e2e"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "^0.3.28"
futures-lite = "^1.13.0"
hyper = { version = "^0.14.26", features = ["client", "http1"] }
hyper-tls = "0.5.0"
libc = "^0.2.142"
mio = "^0.8.6"
serial_test = "^2.0.0"
slab = "^0.4.8"
sozu-command-lib = { path = "../command" }
sozu-lib = { path = "../lib" }
time = "^0.3.20"
tokio = { version = "1.28.0", features = ["net", "rt", "rt-multi-thread"] }
