[package]
name = "sozuctl"
description = "command line application to configure a sozu instance"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozuctl"
homepage = "http://sozu.io"
version = "0.1.1"
license = "AGPL-3.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
categories = ["network-programming"]

[dependencies]
time    = "^0.1.34"
clap    = "^2.19.0"
libc    = "^0.2"
nix     = "^0.7"
mio     = "^0.6"
mio-uds = "^0.6"
rand    = "^0.3"
sozu-lib = { version = "^0.1", path = "../lib" }
sozu-command-lib = { version = "^0.1", path = "../command" }

[features]
unstable = []

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }
